language: node_js
sudo: required
node_js:
  - 10

before_install:
- npm install n
- sudo ./node_modules/.bin/n stable
- rm -rf ~/.nvm

install:
  - npm install mocha
  - npm install

script: sudo npm test
